name: Sphinx build

on: push

jobs:
  sphinx_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Sphinx
        run: |
          sudo apt-get update
          sudo apt-get install python3-sphinx
          cd docs
          ./github_sphinx.sh
          cd ..
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
